using UnityEngine;
using UnityEngine.InputSystem;
using System.Collections;
using System.Threading.Tasks;
using LLMUnity;

public class WizardInteract : MonoBehaviour
{
    [Header("References")]
    [SerializeField] private Transform playerCamera;
    [SerializeField] private Transform wizardTransform;
    [SerializeField] private SpeechBubble wizardSpeechBubble;
    [SerializeField] private PiperSpeakerComponent piperTTS;
    [SerializeField] private PuterSpeaker puterTTS;

    [Header("LLM (Simulation)")]
    // SIMULATION: Drag your LLMCharacter (e.g., MainHub/LLM Manager) here to enable LLM hints.
    // Remove this and the simulation coroutine once the demo is over.
    [SerializeField] private LLMCharacter wizardBrain;
    [SerializeField] private int llmTimeoutMs = 8000;

    [Header("Interaction")]
    [SerializeField] private float interactRange = 5f;
    [SerializeField] private float interactAngle = 30f;

    [Header("Audio")]
    public string wizardVoice = "en_US-ryan-high.onnx";
    public string wizardPuterVoiceId = "onyx"; // OpenAI wizard-like voice

    [Header("Cooldown")]
    [SerializeField] private float cooldown = 3f;

    private float lastInteractTime = -999f;
    private bool introComplete = false;
    private bool isSpeaking = false;
    private System.Action introCallback;

    public SpeechBubble SpeechBubble => wizardSpeechBubble;

    private void Awake()
    {
        if (piperTTS == null) piperTTS = GetComponentInChildren<PiperSpeakerComponent>();
        if (puterTTS == null) puterTTS = GetComponentInChildren<PuterSpeaker>();
        
        if (piperTTS != null) _ = piperTTS.SetVoiceModel(wizardVoice);
        if (puterTTS != null) puterTTS.SetVoice("openai", "tts-1", wizardPuterVoiceId);

        if (piperTTS == null && puterTTS == null)
        {
            //Debug.LogError($"[WizardInteract] CRITICAL: No TTS component (Piper or Puter) found for the Wizard on {gameObject.name}. He will be silent!");
        }
        else
        {
            Debug.Log($"[WizardInteract] Initialized with Piper: {piperTTS != null}, Puter: {puterTTS != null}");
        }
    }

    public void SetIntroCallback(System.Action onComplete)
    {
        introCallback = onComplete;
    }

    public void OnInteract(InputAction.CallbackContext context)
    {
        if (!context.started) return;
        if (!enabled) return;
        if (isSpeaking) return;
        if (wizardSpeechBubble == null || playerCamera == null || wizardTransform == null) return;
        if (Time.time - lastInteractTime < cooldown) return;
        if (!IsLookingAtWizard()) return;

        lastInteractTime = Time.time;

        if (!introComplete)
        {
            StartCoroutine(GreetingSequence());
        }
        else
        {
            GiveContextualLine();
        }
    }

    private void Update()
    {
        // TRIGGER SIMULATION WITH 'P' KEY
        if (Keyboard.current != null && Keyboard.current.pKey.wasPressedThisFrame)
        {
            Debug.Log("[WizardInteract] 'P' key pressed. Starting simulation...");
            RunSimulation();
        }
    }

    [ContextMenu("Run Hint Simulation")]
    public void RunSimulation()
    {
        StopAllCoroutines(); // Reset any active speech
        isSpeaking = false;
        StartCoroutine(SimulationRoutine());
    }

    // ─── SIMULATION ROUTINE ─────────────────────────────────────────────────────
    // TEMPORARY: Remove this entire region when the simulation is no longer needed.
    // Simulates as if the player put 'Heart of the Volcano' wrong in the cauldron.
    //
    // The wizard (Zaldric) will:
    //   - Tier 1: Tell the player how many items were wrong (vague).
    //   - (3s delay)
    //   - Tier 2: Point the player toward the biome (Volcano area) without naming the item.
    //   - (3s delay)
    //   - Tier 3: Identify the specific wrong ingredient the player used (NOT the correct one).
    //
    // Each tier is generated by the LLM with Zaldric's personality as context.
    // If LLM is unavailable, fallback lines are used.
    private IEnumerator SimulationRoutine()
    {
        Debug.Log("[WizardInteract] Simulation starting...");
        
        // Ensure the speech bubble UI is visible
        if (wizardSpeechBubble != null) wizardSpeechBubble.gameObject.SetActive(true);

        // --- Simulated cauldron context ---
        // Pretend the player put 'Moonlit Spider Silk' instead of 'Heart of the Volcano'
        const string simulatedWrongItem  = "Moonlit Spider Silk";
        const string simulatedBiome      = "the Volcano area";
        const int    simulatedWrongCount = 1;

        const string WIZARD_PERSONA =
            "You are Zaldric, an old and wise wizard guardian of a fantasy realm. " +
            "You speak in short, dramatic, in-character sentences (under 25 words). " +
            "You are helping a player fix their potion recipe after a failed cauldron attempt. " +
            "You care deeply about the dragon and the realm. Stay fully in character.";

        // --- TIER 1: Item count (vague) ---
        string tier1Prompt =
            WIZARD_PERSONA + "\n\n" +
            $"The player just failed the cauldron. {simulatedWrongCount} of their 8 ingredients was wrong. " +
            $"Tell them only HOW MANY ingredients were wrong, nothing else. " +
            $"Do NOT name any ingredient or area. Keep it under 20 words.";

        yield return StartCoroutine(AskWizardLLMCoroutine(tier1Prompt,
            /* fallback: */ $"Hmm... {simulatedWrongCount} of those ingredients does not belong in this recipe."));
        string tier1Line = _llmResult;
        yield return StartCoroutine(SayWithVoice(new string[] { tier1Line }));
        yield return new WaitForSeconds(3f);

        // --- TIER 2: Biome proximity ---
        string tier2Prompt =
            WIZARD_PERSONA + "\n\n" +
            $"The player failed the cauldron a second time. One wrong ingredient comes from {simulatedBiome}. " +
            $"Tell them to look more carefully in {simulatedBiome}, without naming the specific ingredient. " +
            $"Keep it under 20 words.";

        yield return StartCoroutine(AskWizardLLMCoroutine(tier2Prompt,
            /* fallback: */ $"Perhaps you should revisit your choice from {simulatedBiome}..."));
        string tier2Line = _llmResult;
        yield return StartCoroutine(SayWithVoice(new string[] { tier2Line }));
        yield return new WaitForSeconds(3f);

        // --- TIER 3: Wrong item identification (NOT the answer) ---
        string tier3Prompt =
            WIZARD_PERSONA + "\n\n" +
            $"The player failed the cauldron a third time. They used '{simulatedWrongItem}' but it is the WRONG ingredient. " +
            $"Tell the player that '{simulatedWrongItem}' is incorrect and should not be in the potion. " +
            $"Do NOT say what the correct ingredient is. Keep it under 25 words.";

        yield return StartCoroutine(AskWizardLLMCoroutine(tier3Prompt,
            /* fallback: */ $"The {simulatedWrongItem} does not belong here. Remove it and think again."));
        string tier3Line = _llmResult;
        yield return StartCoroutine(SayWithVoice(new string[] { tier3Line }));

        Debug.Log("[WizardInteract] Simulation complete.");
    }

    // Coroutine wrapper so we can yield return an async call from a coroutine.
    // Returns via the yieldValue trick.
    private string _llmResult;
    private IEnumerator AskWizardLLMCoroutine(string prompt, string fallback)
    {
        _llmResult = fallback; // default

        if (wizardBrain == null)
        {
            Debug.LogWarning("[WizardInteract] wizardBrain not assigned — using fallback line.");
            yield break;
        }

        bool done = false;
        string rawResponse = "";

        // Fire the async chat and track completion
        wizardBrain.Chat(prompt,
            (chunk) => rawResponse = chunk,
            () => done = true
        );

        // Wait until response is complete OR timeout
        float elapsed = 0f;
        float timeoutSec = llmTimeoutMs / 1000f;
        while (!done && elapsed < timeoutSec)
        {
            elapsed += UnityEngine.Time.deltaTime;
            yield return null;
        }

        if (!string.IsNullOrWhiteSpace(rawResponse))
        {
            string cleaned = rawResponse.Trim();
            // Strip common LLM prefixes
            foreach (string prefix in new[] { "Zaldric:", "Response:", "Hint:", "Answer:" })
            {
                if (cleaned.StartsWith(prefix, System.StringComparison.OrdinalIgnoreCase))
                    cleaned = cleaned.Substring(prefix.Length).Trim();
            }
            if (!string.IsNullOrWhiteSpace(cleaned))
                _llmResult = cleaned;
        }

        // yield return usage trick so the coroutine can 'return' the value:
        // Caller must use: string result = yield return StartCoroutine(AskWizardLLMCoroutine(...));
        // Then read _llmResult immediately after.
    }

    private bool IsLookingAtWizard()
    {
        Vector3 dirToWizard = (wizardTransform.position - playerCamera.position).normalized;
        float angle = Vector3.Angle(playerCamera.forward, dirToWizard);
        float distance = Vector3.Distance(playerCamera.position, wizardTransform.position);

        return angle < interactAngle && distance < interactRange;
    }

    public IEnumerator SayWithVoice(string[] lines, System.Action onDone = null)
    {
        Debug.Log($"[WIZARD] SayWithVoice CALLED with {lines?.Length ?? 0} lines");
        Debug.Log($"[WIZARD] wizardSpeechBubble={(wizardSpeechBubble != null ? wizardSpeechBubble.name : "NULL")}");
        Debug.Log($"[WIZARD] piperTTS={(piperTTS != null ? piperTTS.name : "NULL")}, puterTTS={(puterTTS != null ? puterTTS.name : "NULL")}");

        isSpeaking = true;
        foreach (string line in lines)
        {
            Debug.Log($"[WIZARD] Speaking line: '{line}'");
            // 1. Explicitly trigger TTS
            if (piperTTS != null)
            {
                Debug.Log("[WIZARD] Using piperTTS.Speak");
                piperTTS.Speak(line);
            }
            else if (puterTTS != null)
            {
                Debug.Log("[WIZARD] Using puterTTS.Speak");
                puterTTS.Speak(line);
            }
            else
            {
                Debug.LogWarning("[WIZARD] No TTS available! Line will not be spoken.");
            }

            // 2. Trigger bubble display
            bool lineDone = false;
            if (wizardSpeechBubble != null)
            {
                Debug.Log("[WIZARD] Calling wizardSpeechBubble.Say...");
                wizardSpeechBubble.Say(new string[] { line }, () => lineDone = true);
            }
            else
            {
                Debug.LogWarning("[WIZARD] wizardSpeechBubble is NULL, skipping bubble");
                lineDone = true;
            }

            yield return new WaitUntil(() => lineDone);
            Debug.Log($"[WIZARD] Line finished: '{line}'");
        }
        Debug.Log("[WIZARD] SayWithVoice DONE");
        isSpeaking = false;
        onDone?.Invoke();
    }

    private IEnumerator GreetingSequence()
    {
        bool done = false;
        yield return StartCoroutine(SayWithVoice(new string[]
        {
            "Ah, a visitor! And you brought your little robot friend.",
            "I am Zaldric, guardian of this realm.",
            "Our dragon has fallen terribly ill...",
            "I need eight ingredients to brew a healing potion.",
            "Each ingredient is found close to my magical books.",
            "Choose the ingredient that matches your answer.",
            "Once you have all eight, bring them to the cauldron.",
            "But be warned... I can only tell you how many are wrong.",
            "Not which ones. You must trust your knowledge.",
            "Now go! The dragon does not have much time."
        }, () => done = true));

        introComplete = true;
        introCallback?.Invoke();
        introCallback = null;
    }

    private void GiveContextualLine()
    {
        int collected = IngredientTracker.Instance != null
            ? IngredientTracker.Instance.TotalCollected
            : 0;

        if (FantasyWorldManager.worldComplete)
        {
            string[] lines = {
                "You did it! The dragon is healing as we speak.",
                "I knew you had it in you. The realm is in your debt.",
                "The potion worked perfectly. Thank you, adventurer."
            };
            StartCoroutine(SayWithVoice(new string[] { lines[Random.Range(0, lines.Length)] }, null));
            return;
        }

        if (collected >= 8)
        {
            string[] lines = {
                "You have all eight! Hurry to the cauldron!",
                "The ingredients are gathered. The cauldron awaits!",
                "Quick, to the cauldron! The dragon grows weaker."
            };
            StartCoroutine(SayWithVoice(new string[] { lines[Random.Range(0, lines.Length)] }, null));
        }
        else if (collected > 0)
        {
            string[] lines = {
                $"You have {collected} ingredients so far. Keep searching!",
                $"The dragon stirs... {collected} down, {8 - collected} to go.",
                $"Good progress. {8 - collected} more ingredients needed."
            };
            StartCoroutine(SayWithVoice(new string[] { lines[Random.Range(0, lines.Length)] }, null));
        }
        else
        {
            string[] lines = {
                "The ingredients are scattered across the land. Look for them!",
                "Hurry adventurer, the dragon grows weaker by the minute.",
                "Each station has a book with a question. Choose wisely."
            };
            StartCoroutine(SayWithVoice(new string[] { lines[Random.Range(0, lines.Length)] }, null));
        }
    }

    public void SayFailResult(int failureIteration, int wrongCount, int total)
    {
        Debug.Log($"[WIZARD] SayFailResult CALLED: iteration={failureIteration}, wrongCount={wrongCount}, total={total}");
        
        string[] lines;

        if (failureIteration == 1)
        {
            // Tier 1: Vague — only the count
            if (wrongCount == 1)
            {
                lines = new string[]
                {
                    "So close! Just one ingredient was wrong.",
                    "You can do this. Go back and reconsider."
                };
            }
            else if (wrongCount <= 3)
            {
                lines = new string[]
                {
                    $"Hmm... {wrongCount} of those ingredients do not belong.",
                    "You are close though. Think carefully and try again."
                };
            }
            else
            {
                lines = new string[]
                {
                    $"Oh dear... {wrongCount} ingredients were wrong.",
                    "Perhaps revisit the books at each station.",
                    "Take your time. The answers are all there."
                };
            }
        }
        else if (failureIteration == 2)
        {
            // Tier 2: Proximity — mention the biome/area
            lines = new string[]
            {
                "One of your wrong choices comes from the Volcano area. Check that station again.",
                "Look more carefully at what you collected near the Volcano."
            };
        }
        else
        {
            // Tier 3: Direct — name the wrong ingredient (not the correct one)
            lines = new string[]
            {
                "The Moonlit Spider Silk does not belong in this potion. Remove it and try again.",
                "That ingredient from the silk station is incorrect. Something else goes there."
            };
        }

        StartCoroutine(SayWithVoice(lines, null));
    }
}
